dir:
  env: HOMEPATH
  input: data/in
  output: data/out

file:
  input:
    extension: .dat
    layout:
      format:
        seller: "001"
        client: "002"
        sale: "003"
    delimiter:
      data: "รง"
      items: ","
      itemData: "-"
  output:
    extension: .done.dat
    report:
      simple:
        info:
          clientCount: "Quantidade de clientes: %d"
          sellerCount: "Quantidade de vendedores: %d"
          bestSaleId: "ID da venda mais cara: %s"
          worstSeller: "O pior vendedor: %s"
